[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Quoridor"
authors = [{name = "Orlann FERREIRA"}, {name = "Tommy BRISSET"}, {name = "Thibault CHOUBRY"}, {name = "Yann GELLNER"}]
dynamic = ["version", "description"]